name: PerformantPlants
version: 0.1.0
api-version: '1.15'
author: Kosinkadink
main: me.kosinkadink.performantplants.PerformantPlants
softdepend: [Vault,PlaceholderAPI]
commands:
  plants:
    usage: /<command>
    aliases: [pp]