name: PerformantPlants
version: 0.2.0
api-version: '1.16'
author: Kosinkadink
main: me.kosinkadink.performantplants.PerformantPlants
softdepend: [Vault,PlaceholderAPI,ProtocolLib]
commands:
  plants:
    usage: /<command>
    aliases: [pp]